-- Create badges table in Supabase
CREATE TABLE IF NOT EXISTS public.badges (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    targets INTEGER[] NOT NULL DEFAULT '{1,2,3,4,5}',
    thresholds TEXT[] NOT NULL DEFAULT '{"","","","",""}',
    icon TEXT NOT NULL DEFAULT 'Award'
);

-- Enable RLS
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow public read access" ON public.badges;
DROP POLICY IF EXISTS "Allow service role write access" ON public.badges;
CREATE POLICY "Allow public read access" ON public.badges FOR SELECT USING (true);
CREATE POLICY "Allow service role write access" ON public.badges FOR ALL USING (true);

-- Insert seed data

INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('rope_burner', 'Rope Burner', 'Debate Arena & Tug-of-War', 'Friction burns mean you''ve put everything into pulling the debate rope. Awarded for total votes cast.', '{5,50,250,1000,5000}', '{"5 votes","50 votes","250 votes","1,000 votes","5,000 votes"}', 'Vote') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('trend_breaker', 'Trend Breaker', 'Debate Arena & Tug-of-War', 'Voted for the minority side when it was under 30% and helped pull the momentum back.', '{1,10,50,200,1000}', '{"1 vote","10 votes","50 votes","200 votes","1,000 votes"}', 'RotateCcw') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('crowd_commander', 'Crowd Commander', 'Debate Arena & Tug-of-War', 'Triggers the live traffic simulation to sway the crowds on debate cards.', '{5,25,100,500,2000}', '{"5 triggers","25 triggers","100 triggers","500 triggers","2,000 triggers"}', 'Users') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('debate_architect', 'Debate Architect', 'Debate Arena & Tug-of-War', 'Created hot debates that divided opinions across the arena.', '{1,5,20,100,500}', '{"1 debate created","5 debates created","20 debates created","100 debates created","500 debates created"}', 'MessageSquarePlus') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('hitmans_vanguard', 'Hitman''s Vanguard', 'Debate Arena & Tug-of-War', 'Voted on debates specifically defending Rohit Sharma''s statistics.', '{5,25,100,500,2000}', '{"5 votes","25 votes","100 votes","500 votes","2,000 votes"}', 'Target') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('kings_shield', 'King''s Shield', 'Debate Arena & Tug-of-War', 'Guarded the legacy of Virat Kohli in the debate arena.', '{5,25,100,500,2000}', '{"5 votes","25 votes","100 votes","500 votes","2,000 votes"}', 'Shield') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('thalas_anchor', 'Thala''s Anchor', 'Debate Arena & Tug-of-War', 'Maintained the balance of the rope in MS Dhoni debates.', '{5,25,100,500,2000}', '{"5 votes","25 votes","100 votes","500 votes","2,000 votes"}', 'Anchor') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('heavy_puller', 'Heavy Puller', 'Debate Arena & Tug-of-War', 'Voted on the winning side of debates that ended in a landslide victory (>80% margin).', '{1,10,50,200,1000}', '{"1 time","10 times","50 times","200 times","1,000 times"}', 'Zap') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('iron_grip', 'Iron Grip', 'Debate Arena & Tug-of-War', 'Cast at least one vote in active debates on consecutive days.', '{3,7,15,30,90}', '{"3-day streak","7-day streak","15-day streak","30-day streak","90-day streak"}', 'CalendarCheck') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('the_tie_breaker', 'The Tie-Breaker', 'Debate Arena & Tug-of-War', 'Voted on a debate card that was split exactly 50-50, shifting the balance of power.', '{1,5,20,100,500}', '{"1 time","5 times","20 times","100 times","500 times"}', 'Scale') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('neural_seer', 'Neural Seer', 'Oracle & Predictions (Cricarena)', 'Placed predictions in the multiplayer prediction rooms.', '{5,25,100,500,2000}', '{"5 predictions","25 predictions","100 predictions","500 predictions","2,000 predictions"}', 'Brain') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('calculated_fortune', 'Calculated Fortune', 'Oracle & Predictions (Cricarena)', 'Decimated prediction rooms with accurate outcome selections.', '{3,15,60,300,1000}', '{"3 wins","15 wins","60 wins","300 wins","1,000 wins"}', 'Trophy') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('streak_weaver', 'Streak Weaver', 'Oracle & Predictions (Cricarena)', 'Maintained an active winning streak in match predictions.', '{3,5,8,12,20}', '{"3 wins in a row","5 wins in a row","8 wins in a row","12 wins in a row","20 wins in a row"}', 'Sparkles') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('underdog_alchemist', 'Underdog Alchemist', 'Oracle & Predictions (Cricarena)', 'Backed outside odds (>2.5x multiplier) in prediction matchups and won.', '{1,5,20,100,400}', '{"1 win","5 wins","20 wins","100 wins","400 wins"}', 'Star') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('smart_xi_tactician', 'Smart XI Tactician', 'Oracle & Predictions (Cricarena)', 'Drafted fantasy teams utilizing the Smart XI selection engine.', '{1,10,50,200,1000}', '{"1 squad","10 squads","50 squads","200 squads","1,000 squads"}', 'ClipboardList') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('monte_carlo_survivor', 'Monte Carlo Survivor', 'Oracle & Predictions (Cricarena)', 'Ran full Monte Carlo predictions inside the Oracle Simulation console.', '{5,20,100,400,1500}', '{"5 runs","20 runs","100 runs","400 runs","1,500 runs"}', 'Dices') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('high_roller', 'High Roller', 'Oracle & Predictions (Cricarena)', 'Total coins wagered in prediction games.', '{500,2500,10000,50000,250000}', '{"500 coins","2,500 coins","10,000 coins","50,000 coins","250,000 coins"}', 'Coins') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('the_hedger', 'The Hedger', 'Oracle & Predictions (Cricarena)', 'Covered both outcomes across different matching pools to secure a split payout.', '{1,10,50,200,800}', '{"1 match","10 matches","50 matches","200 matches","800 matches"}', 'Share2') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('clean_sweep', 'Clean Sweep', 'Oracle & Predictions (Cricarena)', 'Predicted every single match outcome correctly in a single day''s schedule.', '{1,3,7,15,45}', '{"1 day","3 days","7 days","15 days","45 days"}', 'ListChecks') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('oracle_override', 'Oracle Override', 'Oracle & Predictions (Cricarena)', 'Won a prediction where you picked the opposite team recommended by the AI.', '{1,5,20,80,300}', '{"1 override","5 overrides","20 overrides","80 overrides","300 overrides"}', 'ToggleRight') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('coin_accumulator', 'Coin Accumulator', 'Economy & Store', 'Unlocked by holding a massive balance of Crinava Coins simultaneously.', '{1000,5000,25000,100000,500000}', '{"1,000 coins","5,000 coins","25,000 coins","100,000 coins","500,000 coins"}', 'PiggyBank') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('patron_of_crinava', 'Patron of Crinava', 'Economy & Store', 'Supported development by purchasing coin packs via the Razorpay interface.', '{1,3,10,25,100}', '{"1 purchase","3 purchases","10 purchases","25 purchases","100 purchases"}', 'CreditCard') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('star_trader', 'Star Trader', 'Economy & Store', 'Upgraded user standing levels within the VIP store packages.', '{1,2,3,4,5}', '{"Basic VIP","Silver VIP","Gold VIP","Platinum VIP","Obsidian VIP"}', 'Star') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('coin_burner', 'Coin Burner', 'Economy & Store', 'Total coins spent buying store cosmetics or raffle rooms.', '{100,500,2500,10000,50000}', '{"100 spent","500 spent","2,500 spent","10,000 spent","50,000 spent"}', 'ShoppingCart') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('daily_collector', 'Daily Collector', 'Economy & Store', 'Collected daily login rewards.', '{5,25,100,300,1000}', '{"5 days","25 days","100 days","300 days","1,000 days"}', 'Calendar') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('ledger_sync', 'Ledger Sync', 'Economy & Store', 'Verified purchases and synced wallets successfully.', '{1,5,25,100,400}', '{"1 sync","5 syncs","25 syncs","100 syncs","400 syncs"}', 'RefreshCw') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('ticket_master', 'Ticket Master', 'Raffle Room (Luck Base)', 'Purchased tickets in the Raffle Room.', '{5,25,100,500,2500}', '{"5 tickets","25 tickets","100 tickets","500 tickets","2,500 tickets"}', 'Ticket') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('raffle_reaver', 'Raffle Reaver', 'Raffle Room (Luck Base)', 'Won items or currency prizes from dynamic raffles.', '{1,5,15,50,200}', '{"1 win","5 wins","15 wins","50 wins","200 wins"}', 'Gift') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('lucky_escape', 'Lucky Escape', 'Raffle Room (Luck Base)', 'Won a raffle where your winning probability was under 5%.', '{1,2,5,15,50}', '{"1 time","2 times","5 times","15 times","50 times"}', 'Clover') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('high_stakes_bidding', 'High Stakes Bidding', 'Raffle Room (Luck Base)', 'Entered premium, high-value coin pools in the Raffle Room.', '{1,5,20,80,300}', '{"1 entry","5 entries","20 entries","80 entries","300 entries"}', 'Gem') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('jackpot_hunter', 'Jackpot Hunter', 'Raffle Room (Luck Base)', 'Entered consecutive raffle draws without missing a cycle.', '{3,10,30,100,400}', '{"3 events","10 events","30 events","100 events","400 events"}', 'Hourglass') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('dna_decoder', 'DNA Decoder', 'Matches & Analytics Telemetry', 'Evaluated profile DNA matches with pro players.', '{1,5,25,100,500}', '{"1 check","5 checks","25 checks","100 checks","500 checks"}', 'Dna') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('telemetry_inspector', 'Telemetry Inspector', 'Matches & Analytics Telemetry', 'Inspected detailed scorecards generated from Cricsheet telemetry logs.', '{5,25,100,500,2000}', '{"5 matches","25 matches","100 matches","500 matches","2,000 matches"}', 'FileText') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('momentum_watcher', 'Momentum Watcher', 'Matches & Analytics Telemetry', 'Examined Match Momentum charts, Heatmaps, and Radar metrics.', '{5,20,80,300,1000}', '{"5 checks","20 checks","80 checks","300 checks","1,000 checks"}', 'LineChartIcon') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('smart_selector', 'Smart Selector', 'Matches & Analytics Telemetry', 'Cast votes on match MVP selection items.', '{3,15,60,250,1000}', '{"3 votes","15 votes","60 votes","250 votes","1,000 votes"}', 'UserCheck') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('global_fan', 'Global Fan', 'Matches & Analytics Telemetry', 'Analyzed matches across different series and tournament tiers.', '{2,4,8,15,30}', '{"2 formats","4 formats","8 formats","15 formats","30 formats"}', 'Globe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('turning_point_spotter', 'Turning Point Spotter', 'Matches & Analytics Telemetry', 'Inspected dynamic Turning Point heatmaps to check momentum shifts.', '{3,15,50,200,800}', '{"3 matches","15 matches","50 matches","200 matches","800 matches"}', 'Radar') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('bloggers_guild', 'Blogger''s Guild', 'Social, Identity & Completionist', 'Read and rated articles on the blog platform page.', '{2,10,40,150,600}', '{"2 blogs","10 blogs","40 blogs","150 blogs","600 blogs"}', 'BookOpen') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('core_identity', 'Core Identity', 'Social, Identity & Completionist', 'Completed auth integration and set up security levels.', '{1,2,3,4,5}', '{"Authentication complete","Custom badge active","Premium display enabled","Full security clearance","Master profile status"}', 'ShieldCheck') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;
INSERT INTO public.badges (id, name, category, description, targets, thresholds, icon) VALUES ('onyx_ascendant', 'Onyx Ascendant', 'Social, Identity & Completionist', 'Earned top-tier Onyx status on multiple achievements.', '{1,3,7,15,30}', '{"1 Onyx badge","3 Onyx badges","7 Onyx badges","15 Onyx badges","30 Onyx badges"}', 'Crown') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, targets = EXCLUDED.targets, thresholds = EXCLUDED.thresholds, icon = EXCLUDED.icon;